# 1.let const var的区别

【6-24】

1. 是否存在变量提升
2. 是否存在暂时性死区
3. 是否允许重复声明变量
4. 是否存在块级作用域
5. 是否能够修改声明的变量



`变量提示`

1. var存在变量提升，可以先使用，后声明
2. let和const必须是先声明后使用，不然报错



`暂时性死区`

1. 只要块级作用域内存在let声明的变量，这个变量就会跟这个区域绑定，不受外部的影响

```js
var temp = 123
if ( true ) {
    temp = 'abc'
    let temp
}
```

2. 只有等到let声明后，变量才可以使用



`允许重复声明变量？`

1. var允许
2. let和const`同一作用域`内重复声明就会报错



`是否存在块级作用域？`





`是否能够修改变量的声明？`

1. let 和 var 声明后，可以修改
2. const声明后不能修改
3. const声明的同时，必须初始化值，不然报错
4. const声明的变量，如果是对象，里面的属性可以更改

# 2. 剩余参数

```js

```





# 3. 延展运算符

```js

```







# 4. promise

Promise是一个构造函数, 

promise是一个对象，也是一个容器，里面存储了异步的操作。



promise用来干嘛的？

解决回调地狱的问题

回调地狱问题是什么问题？

promise特点？

有三种状态,pending resolve reject.

只有promise内部的执行结果能够决定promise的状态

状态不可逆转，如果进入到了resolve,不能够返回pending

promise的api

then

catch

all

race



## 4.1 promis是什么？概念 特点：



### 回调地狱是什么



```javascript
function back() {
    setTimeout(() => {
        console.log(1);
        setTimeout(() => {
            console.log(2);
            setTimeout(() => {
                console.log(3);
            }, 3000);
        }, 2000);
    }, 1000);
}
back();
```



打印出来是







解释：



​	一个函数里面，有一个定时器A，定时器本身就是回调函数，这个定时器A里面又有一个定时器B，定时器B还有一个定时器C，**层层嵌套回调函数，就叫做回调地狱**。



缺点：



```plain
1. 不利于维护，要修改一个，里面其他的全部都要修改。代码的耦合性太差
2. 嵌套太多，可读性差
```



**promise能够解决回调地狱的情况**



### Promise是什么 &.then()



-  是一个**构造函数**，能够new出来一个实例 

-  通过打印我们看到它身上挂载了很多**方法**。每次new出来一个实例，都可以直接调用这些方法。 

-  **.then()**用来**预先指定**，有失败和成功的回调函数 | 失败或者成功 执行什么 error是可选的，result是必选的。 

  ​					  

```javascript
console.dir(Promise)
var p = new Promise();
p.then(result=>{},error=>{});
```



### Promise第三方包



目的：读取文件，按顺序返回内容







太麻烦，回调地狱，回调嵌套回调



而node.js官方提供的fs读取内容模块，**不返回Promise对象**，而我们想利用Promise来实现回调，所以我们要借助**第三方包then-fs**



安装then-fs模块



```plain
npm i then-fs
```



接着的操作是，导入这个模块



```plain
import thenfs from 'then-fs'
```



thenfs名字随便取,



然后调用.then方法，可以只用成功的回调函数，error失败的回调函数是可选参数



```javascript
import thenfs from 'then-fs';

thenfs.readFile('./txt/1.txt', 'utf8').then((r1) => {
    console.log(r1);
});
thenfs.readFile('./txt/2.txt', 'utf8').then((r2) => {
    console.log(r2);
});
thenfs.readFile('./txt/3.txt', 'utf8').then((r3) => {
    console.log(r3);
});
```



到这一步，打印出来的数据还是没有顺序的,还需要进一步完善







### Promise链式调用



.then方法只要前面返回的是一个Promise对象， 就可以进行链式调用。 对上一个Promise对象进行成功的回调处理。



```javascript
import thenfs from 'then-fs';

thenfs.readFile('./txt/1.txt', 'utf8').then((r1) => {
    console.log(r1);
}) // 此时读取第一个文件
```







顺序读取第一和第二个文件时



```javascript
import thenfs from 'then-fs';

thenfs.readFile('./txt/1.txt', 'utf8').then((r1) => {
    console.log(r1);
    return thenfs.readFile('./txt/2.txt', 'utf8');
}).then((r2) => {
    console.log(r2);
}) // 此时读取而来两个文件 按顺序
```







读取三个文件之时



```javascript
import thenfs from 'then-fs';

thenfs.readFile('./txt/1.txt', 'utf8').then((r1) => { // 通过.then1为第一个Promise实例1对象设置回调函数
    console.log(r1);
    return thenfs.readFile('./txt/2.txt', 'utf8');// 通过第一个.then1的回调  return 一个新的Promise实例2 为下一个.then2做准备
}).then((r2) => { // 通过.then2为上一个.then1的返回值 指定成功之后的回调函数
    console.log(r2);
    return thenfs.readFile('./txt/3.txt', 'utf8'); // // 通过第二个.then2的回调  return 一个新的Promise实例3 为下一个.then3做准备
}).then((r3) => {// 通过.then3为上一个.then2的返回值 指定成功之后的回调函数
    console.log(r3);
})
```







### Promise.catch方法



没有设置catch方法，出错的情况。不存在11.txt这个文件







结果：没有提示任何信息，没有报错。而222和333这个数字也打印不出来了。



作用：能够捕获到错误。



如果catch方法放在最后，那么前面的一处地方报错可能导致后面的代码都无法执行。







有报错信息，但是11.txt地方报错，后面的文件也都无法执行。



如果catch紧跟在错误的后面，那么错误提前检测到了，后面的代码可能可以继续被执行。







此时222和333能够成功打印。



综上，catch()方法是不是跟着“可能出错的单元后面是更好的呢！！”



### Promise.all()方法



等待机制。等待所有的异步操作全部执行完毕，再执行下一步的.then操作。



而Promise实例的顺序，就是.all最终打印的顺序



```javascript
import thenfs from 'then-fs'; // 导入模块


var promiseArr = [ // 定义数组
    thenfs.readFile('./txt/3.txt', 'utf8'), // 里面是三个Promise实例对象
    thenfs.readFile('./txt/1.txt', 'utf8'),
    thenfs.readFile('./txt/2.txt', 'utf8'),
] 

// 2. promise all 作用等待机制 所有的promise执行完毕 
// 再执行下一个链式调用
Promise.all(promiseArr).then(([r1,r2,r3]) => {
    console.log(r1,r2,r3);
}).catch(err => console.log(345)).then(res => console.log(123))
```





#### 



```diff
Promise.all([promise1, promise2, promise3]).then(values => {
	// values是数组，里面存储了上面三个对象的结果
} )
```



使用场景：`如何解决，请求并发的问题？`



给页面添加loading效果，希望三个请求导航、头部、底部都好了，再去渲染数据，loading才关闭。



如果一个一个去发送，很占用时间，就用.all的方法去执行。



-  注意，返回的结果，也是和前面的promise的顺序一一对应 
-  注意，只有所有的promise成功了，最后的状态才是resolve，只要有一个是reject，最终的结果就是失败的 



![img](C:/Users/huawei/Desktop/%E9%9D%A2%E8%AF%95/2%20JS%20ES6%E7%AC%94%E8%AE%B02.assets/1657431749679-70316d98-7fea-44c0-8bc9-beff7620c7f4.png)





```diff
        //买作业本
        function cutUp(){
            console.log('挑作业本');
            var p = new Promise(function(resolve, reject){ //做一些异步操作
                setTimeout(function(){
                    console.log('挑好购买作业本');
                    resolve('新的作业本');
                }, 1000);
            });
            return p;
        }

        //买笔
        function boil() {
            console.log('挑笔芯');
            var p = new Promise(function(resolve, reject){ //做一些异步操作
                setTimeout(function(){
                    console.log('挑好购买笔芯');
                    resolve('新的笔芯');
                }, 1000);
            });
            return p;
        }

+        Promise.all([cutUp(),boil()]).then(function(results){
            console.log("写作业的工具都买好了");
            console.log(results);
        });
        
        // 上面的结果
        挑作业本
        挑笔芯
        挑好购买的作业本
        调好购买笔芯
        写作业的工具都好了
        [新的作业本， 新的笔芯] // resolve的结果会放在这个里面
```











### Promise.race方法



是赛跑机制，任何一个异步执行完成，就会去执行下一个.then的回调函数



不会读取所有的Promise实例



```javascript
import thenfs from 'then-fs';


var promiseArr = [
    thenfs.readFile('./txt/2.txt', 'utf8'),
    thenfs.readFile('./txt/3.txt', 'utf8'),
    thenfs.readFile('./txt/1.txt', 'utf8'),
]

// 1. promise race 作用 赛跑机制 有一个promise执行完
// 就立即执行下一个 链式调用
Promise.race(promiseArr).then(([r1,r2,r3]) => {
    console.log(r1,r2,r3);
}).catch(err => console.log(345)).then(res => console.log(123))
```







哪一个文件读取的快就执行哪一个。我们发现打印出来的可能是2也可能是3也可能是1



是赛跑原则，里面只要有一个promise的结果出来了，就会进行下一步then



其他没有执行完毕的异步操作依然会执行，不会停止。只是，一个promise好了，就会立马执行.then

 

注意，只要最先的一个promise是成功的，最先的结果就是成功的。否则就是失败的。



使用场景：缓存的读取，读的是服务器的，还是读的是本地的。哪个更快，就读哪个。做一件事情，超过5s，就不做了，就使用这个方法。



```diff
var promiseArr = [
    thenfs.readFile('./txt/2.txt', 'utf8'),
    thenfs.readFile('./txt/3.txt', 'utf8'),
    thenfs.readFile('./txt/1.txt', 'utf8'),
]
Promise.race([promise1, promise2, promise3]).then(values => {
	//
})
```



另一个race应用



```diff
function requestImg(){
            var p = new Promise(function(resolve, reject){
            var img = new Image();
            img.onload = function(){
               resolve(img);
            }
            img.src = 'xxxxxx';
            });
            return p;
        }

        //延时函数，用于给请求计时
        function timeout(){
            var p = new Promise(function(resolve, reject){
                setTimeout(function(){
                    reject('图片请求超时');
                }, 5000);
            });
            return p;
        }

+        Promise.race([requestImg(), timeout()]).then(function(results){
            console.log(results);
        }).catch(function(reason){
            console.log(reason);
        });
        //上面代码 requestImg 函数异步请求一张图片，timeout 函数是一个延时 5 秒的异步操作。我们将它们一起放在 race 中赛跑。
        //如果 5 秒内图片请求成功那么便进入 then 方法，执行正常的流程。
        //如果 5 秒钟图片还未成功返回，那么则进入 catch，报“图片请求超时”的信息。
```



第一个好的promise出错，最终的结果就是出错的



```diff
let promise1 = new Promise((resolve,reject)=>{
            setTimeout(()=>{
            reject(1);
            },2000)
        });
        let promise2 = new Promise((resolve,reject)=>{
            setTimeout(()=>{
            reject('出错la');
+            },1000)
        });
        let promise3 = new Promise((resolve,reject)=>{
            setTimeout(()=>{
            resolve(3);
            },3000)
        });
        Promise.race([promise1,promise2,promise3]).then(res=>{
            console.log(res);
            //结果：2
        },rej=>{
+          console.log(rej)} // 打印的是这个
        )
```







### Promise.resolve 等价于

new Promise((resolve, reject) => {

​	resolve()

})

### Promise.reject 等价于

new Promise((resolve, reject) => {

​	reject()

})



```diff
Promise有三个状态

pending  等待，new一个promise对象 就是默认这个

fullfilled 成功，resolve执行后，就进入这个

rejected 失败，reject执行后，进入这个状态
```



### 封装读取文件的方法【1】



```javascript
function getFile(fpath) {
    return new Promise()
}
```



1.文件名是**getFile**



2.传递参数fpath 是路径



3.要返回一个Promise实例对象



4.要有一个.then方法



注意：return new Promise  仅仅只是返回了一个形式上的异步对象，因为我们还不知道这个Promise的异步回调是执行ajax请求还是读取文件的请求



```javascript
// 1. 导入读文件的模块
import fs from 'fs';
// 2. 定义getFile函数
function getFile(fpath) {
    return new Promise(function () {
        fs.readFile('./txt/1.txt', 'utf8', (err, dataStr) => {

        })
    })
}
```



到这一步，才能知道是读取文件的回调



同时导入了fs模块，利用fs模块的readFile方法



### 封装读取文件的方法【2】



bug出错，



函数出现bug，函数传参错误。







函数里面的路径写死了，怪不得函数传入的参数是11.txt，不存在这个文件，依然是输出正确的。



```javascript
// 1. 导入读文件的模块
import fs from 'fs';
// 2. 定义getFile函数
function getFile(fpath) {
    return new Promise(function (resolve, reject) {
        fs.readFile(fpath, 'utf8', (err, dataStr) => {
            if (err) return reject(err);
            resolve(dataStr);
        })
    })
}
getFile('./txt/11.txt').then((r1) => {
    console.log(r1);
}).catch((err) => {
    console.log(err);

})
```



1.getFile('./txt/11.txt')返回的是一个Promise对象，



2.then接受了Promise对象，执行回调，



3.里面有正确和错误的回调函数



4.函数getFile里面，return的Promise对象，resolve和reject是形式参数，.then里面的两个是实参，



5.resolve是读取成功，reject是读取失败，这两个顺序和then是一样滴



6.绑定了catch能够打印错误



- 是什么？



是一个对象。



- 里面可以捕获内容，成功执行resolve，失败实行reject



如果想要promise成功执行下去，必须要用.then，如果想要失败执行下去，用.catch



具体操作：



- promise执行成功 进入.then



```plain
new Promise((resolve,reject)=>{resolve("成功执行")}).then(result => alert(result))
```



- promise执行失败 进入catch 没有catch 会报错



```plain
new Promise((resolve,reject) => {reject("执行失败")}).then(result => alert(result))
```



- promise执行失败 进入catch 有catch 打印catch里面的err参数



```plain
new Promise((resolve,reject) => reject("执行失败")).then(result=>alert(result)).catch(err => alert(err))
```



- promise 强制打断与链式操作



链式操作，不是在里面嵌套回调，不是父子级，而是同级的关系



```plain
new Promise((resolve,reject) => resolve(1)).then(result => result + 1).then(result => result + 1).then(result => Promise.reject(new Error(result + "加载失败"))).then(result => result + 1).catch(err => alert(err))
```



注意箭头函数如果没有加花括号 就`不要写return` 不然报错



总结：



```plain
Promise是一个全局对象 通过new的方式创建

里面有回调函数 参数是resolve和reject，成功执行resolve，失败执行reject，必须是这样。

resolve('123')的值想要获取，要在下一次的.then(result => result + 1) 里面获取，result就是123，同理 reject('345')  下一次的链式里面 .catch(err => alert(err)) err就是345 

Promise.reject是promise对象的一个方法，能够强制打断，打断后进入catch 不会再进入.then
```



## 6.2 promise手写原理



### 前言：



```plain
let p1 = new Promise((resolve,reject) => {resolve("执行成功"),reject("执行失败")});
```



输出：执行成功



```plain
let p2 = new Promise((resolve,reject) => {reject("执行失败"),resolve("执行成功")});
```



输出：执行失败



```plain
let p3 = new Promise((resolve,reject) => {throw("执行失败")})
```



输出：执行失败



![img](C:/Users/huawei/Desktop/%E9%9D%A2%E8%AF%95/2%20JS%20ES6%E7%AC%94%E8%AE%B02.assets/db87e7956fa24650bb60902bc3f113b4tplv-k3u1fbpfcp-watermark.webp)



上面的传达的知识点：



1.执行promise里面的resolve，状态会变为fulfilled



2.执行promise的reject，状态会变为rejected



3.以第一次为准 状态不可改变。



4.throw 是报出一个错误



5.值就是调用函数时传递的参数



### 6.3.1 实现自己的resolve和reject函数



下面定义了自己的promise类 里面有初始值 初始this指向  如果调用了这个类里面的resolve和reject方法，将会改变PromiseState状态和PromiseResult值



```javascript
class MyPromise {
      constructor(executor) {
        // 初始值
        this.initValue();
        // 初始this指向
        this.initBind();
        // 执行传进来的函数
        executor(this.resolve, this.reject);
      }
      initBind() {
        // 初始化this
        this.resolve = this.resolve.bind(this);
        this.reject = this.reject.bind(this);
      }
      initValue() {
        // 初始化值
        this.PromiseResult = null;
        // 初始化状态
        this.PromiseState = 'pending';
      }

      resolve(value) {
        // 执行resolve 状态变为fulfilled
        this.PromiseState = 'fulfilled';
        // 值为传进来的值
        this.PromiseResult = value;
      }
      reject(reason) {
        // 执行reject 状态变为rejected
        this.PromiseState = 'rejected';
        // 值为传进来的值
        this.PromiseResult = reason;
      }
    }
    const test1 = new MyPromise((resolve, reject) => {
      resolve("成功")
    });
    const test2 = new MyPromise((resolve, reject) => {
      reject("失败");
    })
    console.log(test1);
    console.log(test2);
```



### 6.3.2 状态不可以改变。



真正的Promise对象 如果实现了，那么就只能以第一次为准。但是在上面的基础上添加



```plain
    const test3 = new MyPromise((resolve, reject) => {
      resolve("执行成功")
      reject("执行失败");
    })
    console.log(test3);
```



打印出来的是执行失败，而不是成功。







解决方法：



```javascript
      resolve(value) {
        // 如果状态不是等待 直接return
        if (this.PromiseState !== 'pending') return
        // 执行resolve 状态变为fulfilled
        this.PromiseState = 'fulfilled';
        // 值为传进来的值
        this.PromiseResult = value;
      }
      reject(reason) {
        // 如果状态不是等待 直接return
        if (this.PromiseState !== 'pending') return
        // 执行reject 状态变为rejected
        this.PromiseState = 'rejected';
        // 值为传进来的值
        this.PromiseResult = reason;
      }
```



加判断条件即可。最终







### 6.3.3 throw测试



- promise中有throw 就会执行reject



```plain
    const test4 = new MyPromise((resolve, reject) => {
      throw ("失败");
    })
    console.log(test4);
```



### 6.3.4 then测试



then方法模拟



```plain
      then(onFulfilled, onRejected) {
        // 两个回调函数 如果就是普通参数 就返回输出 如果是函数 就返回函数名
        onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : val => val;
        onRejected = typeof onRejected === 'function' ? onRejected : err => {
          throw ("请求失败")
        }
        // 判断状态 如果是fulfilled 就执行onFulfilled 回调
        if (this.PromiseState === 'fulfilled') {
          onFulfilled(this.PromiseResult)
          // 如果是 rejected 就执行 onRejected回调
        } else if (this.PromiseState === 'rejected') {
          onRejected(this.PromiseResult)
        }

      }
```



没能执行成功



bind方法：



手动实现bind方法：https://blog.csdn.net/lovefengruoqing/article/details/80186401



bind方法简单：



### 6.3.5 微任务



```javascript
const p = new Promise((resolve,reject) => resolve(1)).then(res => console.log(res) , err => console.log(err)); 
console.log(2)
```



输出 2 1 为什么？



因为then是微任务



then 预先指定里面的err错误回调 和catch的区别：



catch 捕捉错误 后面的代码依旧能够执行



then预先指定，如果报错，后面的代码都无法执行



### 6.3.6 catch和then的执行顺序



- 如果promise内部报错，第一个then不执行 catch执行 后面的then会执行



```javascript
        const promise4 = new Promise((resolve,reject) => {
            throw new Error("test")
        })
        promise4.then(res => console.log(res + '执行了第一次'))
        .catch(err => console.log(err))
        .then(res => console.log('then又被执行了'));
```



- 如果promise内部正确 catch不执行 两个then执行



```javascript
        const promise4 = new Promise((resolve,reject) => {
            resolve("成功")
        })
        promise4.then(res => console.log(res + '执行了第一次'))
        .catch(err => console.log(err))
        .then(res => console.log('then又被执行了'));
```



如果要实现promise内部resolve，只执行then；promise内部reject，只执行catch。第一种的then -> catch -> then第二个部分失效，catch应该在最后



这样



```javascript
        const promise5 = new Promise((resolve,reject) => {
            throw new Error("失败")
        })
        promise5.then(res => console.log(res + '执行了第一次'))
        .then(res => console.log('then又被执行了')).catch(err => console.log(err));
```



### 6.3.7 then 的 第二个回调和catch的区别于关系



```javascript
        const promise = new Promise((resolve,reject) => {
            throw new Error("test");
        })
        // throw前面不能return
        // 1. 当promise内部报错 .then中有两个回调函数时，执行reject而不是catch
        promise.then(
            res =>{resolve(res)},
            err => console.log('reject' + err)
            ).catch(
            err1 => console.log('catch' + err1)
            )

        // 最终打印 rejectError: tests

        // 2.当 promise内部报错 .then一个回调 执行catch
        const promise2 = new Promise((resolve,reject) => {
            throw new Error("test");
        })
        promise2.then(
            res => {
                console.log("resolve" + res);
            }
        ).catch(err => console.log("catch" + err))

        // 3. 网络异常通常会进入catch而不是进入reject


        // 4. 如果promise内部成功 但then第一个函数抛出异常 
        // catch能捕获到 reject捕获不到
        const promise3 = new Promise((resolve,reject) => {
            resolve("成功")
        })
        promise3.then(
            res => {
                throw new Error("错误")
            },
            err => {
                console.log('reject' + err)
            }
        ).catch(err => {
            console.log('catch' + err) // 打印catch
        })
```



### 6.3.8 all和race的区别：



- all 所有机制，所有的异步都执行

- race赛跑机制，哪个promise先执行，所有的就立刻结束



```plain
// 1. promise race 作用 赛跑机制 有一个promise执行完
// 就立即执行下一个 链式调用
// Promise.race(promiseArr).then(([r1,r2,r3]) => {
//     console.log(r1,r2,r3);
// }).catch(err => console.log(345)).then(res => console.log(123))
// 2. promise all 作用等待机制 所有的promise执行完毕 
// 再执行下一个链式调用
Promise.all(promiseArr).then(([r1,r2,r3]) => {
    console.log(r1,r2,r3);
}).catch(err => console.log(345)).then(res => console.log(123))
```



## 6.4 promise解决项目问题







### 2.8 promise的使用和实现

【6-24】

1. 什么是promise
2. 你对promise的理解
3. promise用过吗？
4. `1. 名词约定`

   - 小写的promise指的是Promise的实例对象
   - Promise的P大写，单数，表示Promise的构造函数
   - Promises首字母大写且复数形式 用于指代Promise的规范





### 2.8.2 promise的静态方法

【7-10】

race的场景不够。

```diff
1. Promise.resolve()
2. Promise.reject()
3. Promise.all()
4. Promise.race
```

#### Promise.resolve()等价于

```diff
new Promise((resolve, reject) => {
	resolve()
})
```



#### Promise.reject()等价于

```diff
new Promise((resolve, reject) => {
	reject()
})
```

>Promise有三个状态
>
>pending  等待，new一个promise对象 就是默认这个
>
>fullfilled 成功，resolve执行后，就进入这个
>
>rejected 失败，reject执行后，进入这个状态



#### Promise.all()

```diff
Promise.all([promise1, promise2, promise3]).then(values => {
	// values是数组，里面存储了上面三个对象的结果
} )
```

使用场景：`如何解决，请求并发的问题？`

给页面添加loading效果，希望三个请求导航、头部、底部都好了，再去渲染数据，loading才关闭。

如果一个一个去发送，很占用时间，就用.all的方法去执行。

- 注意，返回的结果，也是和前面的promise的顺序一一对应

- 注意，只有所有的promise成功了，最后的状态才是resolve，只要有一个是reject，最终的结果就是失败的

![image-20220710104816399](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/4575/image-20220710104816399.png)



```diff
        //买作业本
        function cutUp(){
            console.log('挑作业本');
            var p = new Promise(function(resolve, reject){ //做一些异步操作
                setTimeout(function(){
                    console.log('挑好购买作业本');
                    resolve('新的作业本');
                }, 1000);
            });
            return p;
        }

        //买笔
        function boil() {
            console.log('挑笔芯');
            var p = new Promise(function(resolve, reject){ //做一些异步操作
                setTimeout(function(){
                    console.log('挑好购买笔芯');
                    resolve('新的笔芯');
                }, 1000);
            });
            return p;
        }

+        Promise.all([cutUp(),boil()]).then(function(results){
            console.log("写作业的工具都买好了");
            console.log(results);
        });
        
        // 上面的结果
        挑作业本
        挑笔芯
        挑好购买的作业本
        调好购买笔芯
        写作业的工具都好了
        [新的作业本， 新的笔芯] // resolve的结果会放在这个里面

```





#### Promise.race()

是赛跑原则，里面只要有一个promise的结果出来了，就会进行下一步then

>其他没有执行完毕的异步操作依然会执行，不会停止。只是，一个promise好了，就会立马执行.then
>
>注意，只要最先的一个promise是成功的，最先的结果就是成功的。否则就是失败的。

使用场景：缓存的读取，读的是服务器的，还是读的是本地的。哪个更快，就读哪个。做一件事情，超过5s，就不做了，就使用这个方法。

```diff
var promiseArr = [
    thenfs.readFile('./txt/2.txt', 'utf8'),
    thenfs.readFile('./txt/3.txt', 'utf8'),
    thenfs.readFile('./txt/1.txt', 'utf8'),
]
Promise.race([promise1, promise2, promise3]).then(values => {
	//
}) 
```



另一个race应用

```diff
function requestImg(){
            var p = new Promise(function(resolve, reject){
            var img = new Image();
            img.onload = function(){
               resolve(img);
            }
            img.src = 'xxxxxx';
            });
            return p;
        }

        //延时函数，用于给请求计时
        function timeout(){
            var p = new Promise(function(resolve, reject){
                setTimeout(function(){
                    reject('图片请求超时');
                }, 5000);
            });
            return p;
        }

+        Promise.race([requestImg(), timeout()]).then(function(results){
            console.log(results);
        }).catch(function(reason){
            console.log(reason);
        });
        //上面代码 requestImg 函数异步请求一张图片，timeout 函数是一个延时 5 秒的异步操作。我们将它们一起放在 race 中赛跑。
        //如果 5 秒内图片请求成功那么便进入 then 方法，执行正常的流程。
        //如果 5 秒钟图片还未成功返回，那么则进入 catch，报“图片请求超时”的信息。

```



第一个好的promise出错，最终的结果就是出错的

```diff
let promise1 = new Promise((resolve,reject)=>{
            setTimeout(()=>{
            reject(1);
            },2000)
        });
        let promise2 = new Promise((resolve,reject)=>{
            setTimeout(()=>{
            reject('出错la');
+            },1000)
        });
        let promise3 = new Promise((resolve,reject)=>{
            setTimeout(()=>{
            resolve(3);
            },3000)
        });
        Promise.race([promise1,promise2,promise3]).then(res=>{
            console.log(res);
            //结果：2
        },rej=>{
+          console.log(rej)} // 打印的是这个
        )
```







#### promise的catch()方法

【promise的catch应该不属于静态方法】

```diff
function buy () {
            console.log('开始买笔');
            var p = new Promise((resolve, reject) => {
                setTimeout(function () {
                    console.log('买了笔芯');
                    resolve('数学作业');
                })
            })
            return p
        }
        function write () {
            console.log('开始写作业');
            let p = new Promise((resolve, reject) => {
                setTimeout(function () {
                    console.log('写完作业');
                    resolve('作业本')
                })
            })
        }
        buy().then((data) => {
            throw new Error('买了坏的笔芯')
            work(data)
+        }).catch((error) => {
            console.log(error);
        })
        console.log('123');
```



补充详情查看：

https://juejin.cn/post/6941194115392634888#heading-15 里面写的finally方法

https://blog.csdn.net/weixin_43638968/article/details/105258289 这个里面写的then方法





# 5. async和await 异步编程 终极方案



async和await实际上 就是让我们像写同步代码那样去完成异步操作







## await是什么？



-  是一个函数。 

-  作用是：强制等待。 

-  后面跟一个promise对象 

-  必须等到后面的promise对象成功执行resolve，并且返回resolve的结果。如果是reject就会报错。这时需要 try / catch来捕捉错误 



注意点：



- await必须和async配合使用



## async是什么？



-  也是一个函数 

-  作用：标记这个函数是异步操作。因为await等待，后面的时间可能是10s也可能是100000s。JS是单线程，就会造成程序的锁死。所以async的作用是当前函数相较于其它函数操作是异步。而在这个函数里面，await加上后，会像同步代码一样去执行异步代码。 

-  **async必须修饰 最近一级的父函数名**【很容易出错】 



async和await结合 异步代码总是最后一个执行



```plain
如下图，先打印2 再打印456 789 最后是1234
```







注意async修饰的函数内部，不是立即打印456 789 再过5s打印1234。而是先过5s，再打印456 789 最终1234.一起打印，



```plain
如果想让2最后打印，可以如下改造，
```







```plain
    async test() {
      const res = await new Promise((resolve) => {
        setTimeout(function () {
          resolve("1234");
        }, 5000);
      });
      console.log(456);
      console.log(789);
      console.log(res);
    },
    async test1() {
      await this.test();
      console.log(2);
    },
```



错误捕获 await只会等待Promise成功了进入成功函数，捕获不到错误的情况。如下，不捕获不到错误，还会报错。







```plain
async getError() {
      const result = await new Promise((resolve, reject) => {
        reject("失败了");
      });
      console.log(result);
    },
```



解决方案 用try/catch



```plain
async getError() {
      try {
        const result = await new Promise((resolve, reject) => {
          reject("失败了");
        });
        console.log(result);
      } catch (err) {
        alert(err);
      }
```



成功打印  失败了



## 总结：



```plain
await配合async能够让函数里面的异步操作像同步。一起打印，像同步。执行顺序还是异步最后
async标记函数是异步操作，相较于其它函数。await是强制等待函数的执行。
如果像改变函数执行顺序，可以加async和await来最后执行。项目中的需求结合
如果要捕获错误，用try / catch
```



# async 和 await的使用



原本使用.then很麻烦



```javascript
import thenfs from 'then-fs';

function getFile(fpath) {
    const r1 = thenfs.readFile(fpath, 'utf8').then((r1) => {
        console.log(r1);
    }).catch(err => console.log(err)
    );
}
getFile('./txt/11.txt');
```



缺点：



1.代码冗余 2.可读性差







## 使用async 和 await



async 和await的语法



- async



普通函数加了async 打印返回的也是promise对象



肯定是成功的状态



```plain
      async function a() {
        return 1
      }
      console.log(a())
```





https://juejin.cn/post/7007031572238958629



https://juejin.cn/post/6844903742223941645



https://juejin.cn/post/6844903734321872910



https://juejin.cn/post/6844903621360943118



-  ES8新增语法，用来简化异步操作。 

-  出现之前，只能通过.then的方式来处理异步操作。 

-  第一个await前面的代码同步执行， 

-  await后面的代码异步执行。 

-  如果不加await，输出的是Promise对象.【thenfs.readFile 默认返回是Promise对象，有await，返回的是具体的值。其它的Promise对象也是这样】。 







加了await之后



```javascript
import thenfs from 'then-fs';

async function getFile(fpath) {
    const r1 = await thenfs.readFile(fpath, 'utf8');
    console.log(r1);
}
getFile('./txt/1.txt');
```



用法：



1.在thenfs前面加上await



2.在function前面加上async



3.加上之后thenfs.readFile(fpath, 'utf8')返回的是读取文件的内容。如果不加，返回的是Promise实例对象







文件路径错误，不存在11.txt这个文件



打印失败时,能够报错







## async和await的注意事项



1.必须在函数前加async和，thenfs前加await



2.第一个await前面的代码是同步执行，第一个await后面的代码都是异步执行。【也就是函数内await后面所有的代码都会等到同步的执行完毕再执行】



不加await和async的执行顺序



```javascript
import thenfs from 'then-fs';

console.log('A');
function getFile() {
    console.log('B');
    const r1 = thenfs.readFile('./txt/1.txt', 'utf8');
    console.log(r1);
    const r2 = thenfs.readFile('./txt/2.txt', 'utf8');
    console.log(r2);
    const r3 = thenfs.readFile('./txt/3.txt', 'utf8');
    console.log(r3);
    console.log('D');
}
getFile();
console.log('C');
```







没有加，那就所有的都按照顺序依次执行。返回Promise实例对象，不代表就是异步任务。



但是加了



```javascript
import thenfs from 'then-fs';

console.log('A');
async function getFile() {
    console.log('B');
    const r1 = await thenfs.readFile('./txt/1.txt', 'utf8');
    console.log(r1);
    const r2 = await thenfs.readFile('./txt/2.txt', 'utf8');
    console.log(r2);
    const r3 = await thenfs.readFile('./txt/3.txt', 'utf8');
    console.log(r3);
    console.log('D');
}
getFile();
console.log('C');
```







原因是因为函数内部的await后面的所有代码都异步执行了，所以B打印完，会先退出函数，去打印C，然后再去打印r1,r2,r3和D







# 6. generator函数

```js
是什么：
	1. generator函数和普通的函数不一样。普通的函数会一下子直接执行，但是generator函数可以一步一步的执行。
怎么用：
	1. 使用方式要在function后面加上*号
	2. 关键字方法，yield next()方法 yield* for of
      2.1 直接调用generator函数返回的是一个迭代器对象
      2.2 暂停，执行时 碰到yield关键字就暂停。
      2.3 继续 迭代器对象.next（）方法，能够让generator函数继续执行。next方法传参会赋值给yield关键字后面的整体。打印next执行结果，value值就是next传递的参数
		2.4 for of 进行遍历。[场景：generator函数里面调用generator函数是没有效果的。]
    3. this指向 generator函数会返回一个迭代器实例，不能够被当成普通的函数，不是this指向的实例。不能通过new来创建。
      解决：可以创建一个新的对象，通call()方法让generator函数的this指向新的对象实例
    4. 场景
	
```



1. 函数声明和普通函数不一样，必须在function加上*

```js
function* go(str) {
    console.log(1)
    let a = yield str
    console.log(2)
    let b = yield a
    console.log(3)
    return b
}
```

当我们调用函数时

>let it = go('a的值') // 没有返回任何值。

我们尝试debugger一下,没有进去

```diff
        function* go(str) {
+            debugger
            console.log(1)
            let a = yield str
            console.log(2)
            let b = yield a
            console.log(3)
            return b
        }
        let it = go('a的值') // 给到str
```

打印it,生成的是迭代器。我们把它理解为可以帮助我们一步一步输出参数的工具

```js
        let it = go('a的值') // 给到str
        console.log(it);
```

![image-20220801211432393](C:/Users/huawei/Desktop/%E9%9D%A2%E8%AF%95%E9%A2%98%E6%B5%8B%E8%AF%95/%E5%89%8D%E7%AB%AF%E6%89%8B%E5%86%8C/3%20ES6.assets/image-20220801211432393.png)



2. 开始执行时

注意yield，是一个暂停的标志，碰到它，函数会暂停

执行it.next()方法,go('参数') =》赋值给str，碰到yield 就会退出

![image-20220801211735987](C:/Users/huawei/Desktop/%E9%9D%A2%E8%AF%95%E9%A2%98%E6%B5%8B%E8%AF%95/%E5%89%8D%E7%AB%AF%E6%89%8B%E5%86%8C/3%20ES6.assets/image-20220801211735987.png)

```diff
        function* go(str) {
            console.log(1)
            let a = yield str
            console.log(2)
            let b = yield a
            console.log(3)
            return b
        }
        let it = go('a的值') // 给到str
        console.log(it);
+        let r1 = it.next() // 打印 1
```



执行下一个next()时，赋值[next里面的参数赋值给b] -》碰到yield 退出

```diff
        function* go(str) {
            debugger
            console.log(1)
            let a = yield str
            console.log(2)
+            let b = yield a
            console.log(3)
            return b
        }
        let it = go('a的值') // 给到str
        console.log(it);
        let r1 = it.next() // 打印 1
        console.log(r1); // 因为yield str这句话 打印对象 {value: 'a的值', done: false}
+        let r2 = it.next('b的值') // 打印2
```

![image-20220801212050563](C:/Users/huawei/Desktop/%E9%9D%A2%E8%AF%95%E9%A2%98%E6%B5%8B%E8%AF%95/%E5%89%8D%E7%AB%AF%E6%89%8B%E5%86%8C/3%20ES6.assets/image-20220801212050563.png)







# 7. set和map



```js
set
1. set是一种数据结构



map
```



## set

```js
let set = new Set()
// 1. add 添加值
set.add(1)
set.add(2)
set.add(3)
console.log(set); // 包含 1 2 3
set.add(3) // 并不能添加成功

// 2. delete 删除成员
console.log(set.delete(1)); // 删除成功返回true
console.log(set.delete(4)); // false 不存在这个值

// 3. has(val) 判断是否有这个成员
console.log(set.has(2)); // true

// 4. clear清空
set.clear()
console.log(set); // 空的set

// 5. Array.from(set)
set.add(1)
set.add(2)
set.add(3)
// 用新的变量接受
let arr = Array.from(set)
console.log(arr); // [1, 2, 3]
```



可以用迭代器进行遍历

```js
keys()：返回一个键名的遍历器
values(): 返回一个键值的遍历器
entries(): 返回一个键值对的遍历器
forEach(): 使用回调函数遍历每个成员
```





## WeakSet

为什么需要WeakSet？



```js
1. 只能存对象 其它报错
2. 存储对象是弱引用。垃圾回收机制自动回收。不会考虑该对象是否存在内存中 Weak是不可以遍历的。
3. 只有 has add delete方法
没有clear size方法
```









## map

```js
1. 方法
get
set 
has
delete
clear
2. 和object区别：
- 支持其它类型作为属性 不仅仅是字符串
- 能够记住键的原始插入顺序 任何值都可以作为一个键或者值
- 提供了值-值的，对hash的完美实现 -？什么意思
```







## WeakMap





# 8. proxy对象

```js
1. 他是一个拦截器，当我们要访问或者修改一个对象时。也可以拦截一个函数的调用！
2. 他有get set has apply方法
get用于访问的拦截
set用于修改的拦截
has用于判断某个对象是否有这个属性 可以隐藏属性
apply用于方法的拦截
3. 应用场景：
可以用于参数的规则校验 比如说数据类型和值的大小
vue3就是对 对象进行了整体的proxy封装，而不是对每个属性进行监听
4. vue3就是利用proxy的原理，不是一层层的遍历对象里面的属性。而是监听整个对象的操作
继续学习：如果防止内存泄露？vue3响应式原理是什么？
```



`拦截层`

外界要访问一个对象，或者是赋值，必须要通过这个拦截层。拦截层能够对外界的访问进行过滤和改写。

```js
let obj = {
	name = '123'
}
let proxy = new Proxy(target, handler)// target是目标对象,handler是对应的操作 比如获取，比如set赋值的函数

```



## 设置get方法拦截，不存在的对象

```js
let obj = {
    name: '123'
}
// obj 要拦截的对象
// 第二个回调函数 =》 里面添加方法
let proxy = new Proxy(obj, {
    get: function (target, property) {
        if (property in target) {
            return target[property]
        } else {
            // 前面不加throw
            throw new ReferenceError('访问的属性不存在')
        }
    }
})
// 必须针对Proxy对象 而不是原本的对象
console.log(proxy.age);
```





## set拦截赋值操作

修改值，嘿，你想改值吗？不是想改就改的呀，要经过我set的同意

```js
// 1. set方法 赋值时拦截
        // 2. 写法 
        let obj3 = {
            name: 'xiaohang'
        }
        let proxy3 = new Proxy(obj3, {
            // obj 对象
            // prop 拦截的属性
            // value 拦截的值
            set: function (obj, prop, value) {
                if (prop === 'age') {
                    if (!Number.isInteger(value)) {
                        throw new Error('年龄不是整数')
                    }
                    if (value > 60) {
                        throw new Error('年龄不能大于60')
                    }
                }
            }
        })

        proxy3.age = 19
        console.log(obj3);
        // 注意这里不能写 obj.age 而是要写proxy3.age
        // proxy.age = 61
```





## has能够进行属性的隐藏

has操作，我理解的意思是，嘿，你想访问里面的对象吗？但是我可以悄咪咪的隐藏一些属性，就是不让你看见呢！

```js
// has可以隐藏某些属性 不被in操作符发现
        let user = {
            username: 'lizhihang',
            age: '19'
        }
        let handler2 = {
            has(target, key) {
                console.log('target', target);
                console.log('key=', key);
                if (key[0] === 'u') {
                    return false
                }
                return key in target
            }
        }
        let proxy = new Proxy(user, handler2)
        console.log('age' in proxy); // true 能够显示
        console.log('username' in proxy); // false 被隐藏
```



## apply

拦截函数的调用。意思是，嘿，小函数，你在执行之前，必须要经过我apply大哥审一审，通过了你才能继续执行哦

```js
/* 
        2. es6的handler拦截 handler拦截后，返回的是拦截器函数里面的变量
        */

        // apply方法
        // 函数调用时的拦截
        // new Proxy(函数，函数调用前的拦截操作)
        // proxy()表示调用
        let target = (msg) => {
            return msg
        }
        let handler = {
            // target 目标对象 要拦截的函数
            // 目标对象的上下文对象 this
            // 目标对象的参数数组
            apply(target, ctx, args) {
                // console.log('target', target);
                // console.log('ctx', ctx);
                // console.log('args', args);
                return 'hello'
            }
        }
        let proxy2 = new Proxy(target, handler)
        console.log(proxy2('张三')); // 返回一个字符串

        var twice = {
            apply(target, ctx, args) {
                return Reflect.apply(...arguments) * 2
            }
        }
        function sum(left, right) {
            return left + right
        }
        var proxy = new Proxy(sum, twice)
        console.log(proxy.call(sum, 1, 2)); // 6
        console.log(proxy.apply(sum, [1, 9])); // 20
```





## 应用场景1

参数校验的书写

```js
class Person {
    constructor(name, age) {
        debugger
        this.name = name
        this.age = age
        // 因为返回的是validator函数的调用
        // validator函数返回的是一个proxy对象
        // 因此new Person实例 就是一个proxy对象 person.name = 'lizhihang' 就会触发proxy对象的set方法 经过校验函数
        return validator(this, personValidator)
    }
}
const personValidator = {
    name(value) {
        debugger
        return typeof value === 'string'
    },
    age(value) {
        return value >= 18 && typeof value === 'number'
    }
}

function validator(target, validator) {
    return new Proxy(target, {
        _validator: validator,
        set(target, key, value) {
            debugger
            if (target.hasOwnProperty(key)) {
                let v = this._validator[key]
                if (v(value)) {
                    return Reflect.set(target, key, value)
                } else {
                    throw new Error(`不能给 属性${key}设置值`)
                }
            } else {
                throw new Error(`${key}属性不存在`)
            }
        },
    })
}
let person = new Person()
person.name = 'lizhihang'
console.log(person);
```





## 应用场景2

```js
<input type="text" id="txtInput">
<p id="extP">123</p>
<script>
    // 0 获取dom元素
    let iInput = document.getElementById('txtInput')
    let iP = document.getElementById('extP')
    // 1 handler方法和obj对象
    let obj = {
        text: ''
    }
    let handler = {
        get(target, key, value, receiver) {
            console.log(`访问到属性值是${target[key]}`);
            // 打印值
            Reflect.get(target, key, value, receiver)
            console.log(obj);
            console.log(p2);
            return
        },
        set(target, key, value, receiver) {
            debugger
            if (target.hasOwnProperty()) {
                iInput.value = value
                iP.innerHTML = value
                console.log(`监测到值修改为${value}`);
                // 修改值
                Reflect.set(target, key, value, receiver)
                console.log(obj);
                console.log(p2);
             }
            return
        },
        defineProperty(target, key, value, receiver) {
            debugger
            console.log(target, key, value, receiver);
            // 如果加了这个拦截器 那么必须要返回一个Reflect.defineProperty(target, key, value) 
            // 不然就会设置值失败
            // Reflect.defineProperty 就是为对象来定义属性
            return Reflect.defineProperty(target, key, value)
        }
    }
    // 2 new Proxy对象
    let p2 = new Proxy(obj, handler)
    iInput.addEventListener('keyup', function (e) {
        p2.text = e.target.value
    })


</script>
```



proxy小结：

1. proxy是一个拦截器，我们可以给对象包装为proxy对象
2. 当我们要访问 修改 这个对象的值的时候，可以进行一些拦截操作
3. 有set get方法，分别用于赋值和访问值的拦截。has是用来



# 9. symbol

```js
1. symbol是一种数据类型 是ES7新增的
2. 他表示独一无二的值可以通过 Symbol函数生成
3. 如果我们要给一个对象增加一个方法或者属性，但是希望这个属性或者方法和其他对象不要发生重复时，就可以用symbol
4. 使用的方式是 通过函数Symbol生成一个symbol值，可以传入参数，然后把这个值作为属性给到对象，注意要加上[]，不然会被认为是简单的字符串。
5. 也可以用Object.defineProperty

可以看代码的示例
```







# 10. 谈谈你对于解构赋值的理解

## 数组

```js
// 1. 解构赋值 - 交换变量 
let a = 'b'
let b = 'a'
console.log(a, b); // 这句代码去掉 会报错，但是我就实在有点想不通是为什么
[a, b] = [b, a]
console.log(a, b);
```





```js
// 2. 解构赋值 能够进行变量的排序
let num1 = 30
let num2 = 10
let num3 = 40
let num4 = 20
console.log(num1, num2, num3, num4);
[num1, num2, num3, num4] = [num2, num4, num1, num3]
console.log(`第一: ${num1}, 第二：${num2}, 第三：{num3}, 第四：{num4}`);
```





```js
// 3. 解构赋值 只从数组中 取出一部分值
const arr = ['蛋同学', '鸡同学', '鸭同学', '鹅同学', '牛同学', '羊同学']
const [num1, num2, num3] = arr
console.log(`第一名${num1} 第二名${num2} 第三名${num3}`);// 第一名蛋同学 第二名鸡同学 第三名鸭同学
```



```js
// 4 只解构数组里面的部分值 其余用逗号跳过
const arr = ['蛋同学', '鸡同学', '鸭同学', '鹅同学', '牛同学', '羊同学']
const [, , num3, , num5] = arr
console.log(`第三名：${num3}，第五名: ${num5}`); // 第三名：鸭同学，第五名: 牛同学
```





```js
// 5 这种写法应该是错的，第四句代码是报错的 
const arr = ['蛋同学', '鸡同学', '鸭同学', '鹅同学', '牛同学', '羊同学']
let num3 = '狗同学'
let num5 = '猪同学'
// [, , num3, , num5] = arr
```





```js
// 6 能够给解构不到的值 添加默认值
const arr = ['蛋同学', '鸡同学', '鸭同学', '鹅同学', '牛同学', '羊同学']
let [, , num3, , num5, , num7 = '鹿同学'] = arr
console.log(num3, num5, num7); // 鸭同学 牛同学 鹿同学
```



```js
// 7 能够用对象的形式 解构 这样结构更加的清晰
const arr = ['蛋同学', '鸡同学', '鸭同学', '鹅同学', '牛同学', '羊同学']
const { 2: num3, 4: num5 } = arr
console.log(num3, num5); // 鸭同学 牛同学
```



```js
// 8 能够解构数组里面特定的几个数据 其余的用一个参数【剩余参数 保存起来】
const arr = ['蛋同学', '鸡同学', '鸭同学', '鹅同学', '牛同学', '羊同学']
const [num1, num2, num3, ...restNum] = arr
console.log(num1, num2, num3, restNum); // 蛋同学 鸡同学 鸭同学 ['鹅同学', '牛同学', '羊同学']
```





```js
// 9 解构第一个数据
const arr = ['蛋同学', '鸡同学', '鸭同学', '鹅同学', '牛同学', '羊同学']
const [notExist = '数组为空'] = arr
console.log(notExist); // 蛋同学、
```



```js
// 10 就是数组的拷贝
const arr = ['蛋同学', '鸡同学', '鸭同学']
const [...copyArr] = arr
console.log(copyArr);
copyArr[0] = 1
console.log(copyArr);
console.log(arr); // 还是原样
```





## 对象



```js
// 11 从对象里面解构出特定的属性 采用{}的形式
const obj = {
    id: '1',
    name: '蛋老师',
    age: 18,
    gender: '男',
    email: '1111'
}
const { name: eggName, email: eggEmail } = obj
console.log(eggName, eggEmail); // 蛋老师 1111
```



```js
// 12 从对象里面解构出特定的属性 解构时 利用已有数组里面的值 作为属性 注意[arr[0]]这个写法 最外层有一个方括号(对象的键只能是字符串，加[]表示计算，结果是字符串，不加就会报错)
const obj = {
    id: '1',
    name: '蛋老师',
    age: 18,
    gender: '男',
    email: '1111'
}
const arr = ['name', 'email']
const { [arr[0]]: eggName, [arr[1]]: eggEmail } = obj
console.log(eggName, eggEmail); // 蛋老师 1111
```



```js
// 13 对象解构 取名
const obj = {
    id: '1',
    name: '蛋老师',
    age: 18,
    gender: '男',
    email: '1111'
}
const { name: eggName, email: eggEmail } = obj
console.log(eggName, eggEmail); // 蛋老师 1111
```





```js
// 14 对象解构 剔除掉一部分不要的属性
const obj = {
    id: '1',
    name: '蛋老师',
    age: 18,
    gender: '男',
    email: '1111'
}
const { id, age, ...resObj } = obj
console.log(resObj); // {email: "1111", gender: "男", name: "蛋老师"}
```





```js
// 10 对象解构 已有的一个变量 根据对象里面的数据 改值
const obj = {
    id: '1',
    name: '蛋老师',
    age: 18,
    gender: '男',
    email: '1111'
}
// let 后面最好加个分号 不然格式有误
let gender = '女';
({ gender } = obj)
console.log(gender);
```





```js
// 16 对象解构 从嵌套对象里面解构出值
const obj = {
    name: '蛋老师',
    skills: {
        cook: {
            main: '炒鸡蛋',
            language: {
                frontEnd: 'javaScript',
                backEnd: java
            }
        }
    }
}
let { skills: {
    language: { frontEnd }
} } = obj
```



```js
// 17 传递对象给函数 -> 函数转化为数组 返回数组 -> 我们再从中解构
function getAPI(data) {
    return [data.name, data.age]
}
const [eggName, eggAge] = getAPI({ name: '蛋老师', age: 18 })
console.log(eggName, eggAge); // 蛋老师 18
```



```js
// 18 从数组里面解构出一个个对象的属性name和age
const arr = [
    { name: '蛋老师', age: 18 },
    { name: '鸡老师', age: 28 },
    { name: '鸭老师', age: 38 },
]
arr.forEach(({ name, age }) => {
    console.log(`姓名：${name} 年龄${age}`);
})
```

## 字符串

```js
// 19 解构字符串
const str = '蛋老师'
const [first, second, third] = str
console.log(first, second, third); // 蛋 老 师
```



```js
// 20 获取数组的每一项的第一个字符
const arr = ['蛋同学', '狗同学', '鸡同学', '鸭同学', '鹅同学', '牛同学']
arr.forEach(([item], index) => {
    console.log(item); // 获取数组的每一项的第一个字符
})
```

## map

```js
// 20 map 只解构里面的值出来
let map = new Map()
map.set('name1', '蛋老师')
map.set('name2', '猪老师')
map.set('name3', '鸡老师')

for (let [, value] of map) {
    console.log(value); // 蛋老师 猪老师 鸡老师 只打印里面的值 不打印里面的键
}
```



```js
// 21 一般引入一个第三包包 要从里面里面引入方法 就用这样的方式 是按需引入
import name from 'b'
const { good } = name
```

## 正则

```js
// 23 从正则表达式中解构值出来
const str = '再见了886爱你20'
const arrReg = /(\D+)(\d+)(\D+)(\d+)/.exec(str)
const { 1: bye, 3: loveYou } = arrReg
console.log(bye, loveYou); // 再见了 爱你
```









1. 







# 11.对象的方法



## hasOwnProperty

- obj.hasOwnProperty('a') 判断对象obj本身是否有这个属性，不会去原型链上面找【浅拷贝有用到这个方法】

```js
var obj = {
    a: 1,
    fn: function(){
 
    },
    c:{
        d: 5
    }
};
console.log(obj.hasOwnProperty('a'));  // true
console.log(obj.hasOwnProperty('fn'));  // true
console.log(obj.hasOwnProperty('c'));  // true
console.log(obj.c.hasOwnProperty('d'));  // true
console.log(obj.hasOwnProperty('d'));  // false, obj对象没有d属性
 
var str = new String();
// split方法是String这个对象的方法，str对象本身是没有这个split这个属性的
console.log(str.hasOwnProperty('split'));  // false
console.log(String.prototype.hasOwnProperty('split'));  // true
```





# 12. map weakmap set weakset

map

```diff
1. 一种数据结构
key - value的形式，key可以是非字符串型的，可以是引用数据类型的。也可以是value - value的形式

2. 方法
var map = new Map()
map.set(key, value)
map.get(key)
map.has(key)
map.size()
map.delete(delete)
```





weakmap



set

```diff
1. set也是一种数据结构，类似数组，但是里面的值不重复
2. 
set.add(1)
set.delete(0)
set.has()
set.size()
```





weakset
